In [27]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, precision_score

In [259]:
# prepare data frame
df = pd.read_csv('data/Test1.csv')
df_x = df[['X1','X2']]
df_y = df[['Y']]

In [260]:
x_train, x_test, y_train, y_test = train_test_split(df_x,df_y,test_size=0.4,random_state=1)

In [261]:
sc = StandardScaler()
sc_x_train = sc.fit(x_train).transform(x_train)
sc_x_test = sc.fit(x_train).transform(x_test)
sc_x_train # standard value

array([[ 0.31234752,  1.        ],
       [-1.56173762, -1.        ],
       [ 0.31234752, -1.        ],
       [ 0.78086881,  1.        ],
       [-1.09321633, -1.        ],
       [ 1.2493901 ,  1.        ]])

In [262]:
# model
model_logistic = LogisticRegression()
model_logistic.fit(sc_x_train,np.ravel(y_train))

LogisticRegression()

In [263]:
b1 = model_logistic.coef_ # b1, b2
b1

array([[ 1.02209566, -0.02457089]])

In [264]:
b0 = model_logistic.intercept_ # b0
b0

array([-0.03587847])

In [265]:
x = sc_x_test[0,:] # x1, x2
x

array([0.78086881, 1.        ])

In [266]:
y = b1*x + b0
y

array([[ 0.76224416, -0.06044935]])

In [267]:
# predict
y_pred = model_logistic.predict(sc_x_test)
y_pred

array([1, 0, 1, 0], dtype=int64)

In [268]:
# evaluation
con_matrix = confusion_matrix(y_test,y_pred)
con_matrix

array([[1, 1],
       [1, 1]], dtype=int64)

In [269]:
precision_score(y_test,y_pred)

0.5