In [18]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import rand_score, silhouette_score, cluster

df = pd.read_csv('Iris.csv')

In [7]:
x = df[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]]
y = df[["Species"]]

In [8]:
model = KMeans(n_clusters=5, random_state = 0)
model.fit(x)

KMeans(n_clusters=5, random_state=0)

In [9]:
cls_id = model.labels_

# Evaluate by Rand Index/Score and Sum Square Error

In [10]:
cls_id.shape

(150,)

In [11]:
y['Species'].values

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [12]:
cls_id

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 4, 4, 4, 2, 4, 2, 4, 2, 4, 2, 2, 2, 2, 4, 2, 4,
       2, 2, 4, 2, 4, 2, 4, 4, 4, 4, 4, 4, 4, 2, 2, 2, 2, 4, 2, 4, 4, 4,
       2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2, 1, 4, 3, 1, 1, 3, 2, 3, 1, 3,
       1, 1, 1, 4, 1, 1, 1, 3, 3, 4, 1, 4, 3, 4, 1, 3, 4, 4, 1, 3, 3, 3,
       1, 4, 4, 3, 1, 1, 4, 1, 1, 1, 4, 1, 1, 1, 4, 1, 1, 4])

In [13]:
# Rand score
ri = rand_score(y["Species"],cls_id)
ri

0.8432214765100671

In [21]:
# Entropy
contingency_matrix = cluster.contingency_matrix(y, cls_id)

mij = contingency_matrix
mi = contingency_matrix.sum(axis=0)
pij = mij/mi

log2pij = np.log2(pij,out=np.zeros_like(pij), where=(pij!=0))
print(pij.round(2))
print(log2pij.round(2))

ei = pij*log2pij
ei = -1*ei.sum(axis=0)
print('e_i \n', ei.round(2))

m = contingency_matrix.sum()

entropy = ((mi/m)*ei).sum()
print('entropy =', entropy )

[[1.   0.   0.   0.   0.  ]
 [0.   0.   0.96 0.   0.64]
 [0.   1.   0.04 1.   0.36]]
[[ 0.    0.    0.    0.    0.  ]
 [ 0.    0.   -0.05  0.   -0.65]
 [ 0.    0.   -4.81  0.   -1.47]]
e_i 
 [-0.   -0.    0.22 -0.    0.94]
entropy = 0.26795755990651343


In [22]:
# Purity
purity_i = np.amax(contingency_matrix, axis=0)
purity = np.sum(purity_i) / np.sum(contingency_matrix)
purity

0.9066666666666666

In [14]:
# SSE
sse = model.inertia_
sse

46.56163015873017

In [15]:
# Silhouette Coefficient
sil_coeff = silhouette_score(x, cls_id, metric='euclidean')
sil_coeff

0.49285559183161204